import type { Metadata } from "next";
import { raleway } from "@/app/ui/fonts";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from 'geist/font/sans'
import "./globals.css";
import Navbar from "./ui/Navbar";
import { Providers } from './providers';


export const metadata: Metadata = {
    title: "SFU Gaming & Esports Club",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${GeistSans.className}`}>
					<Navbar />
					{children}
			</body>
		</html>
	);
}
